# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43199213b13d8a66559a0f728ad7444b3356766147f8221237bfdba4abc199c11ca0af131650494b537690a170bfdf45045d9f4e27cfdaaace634eac30fe8e14

test:
  secret_key_base: 51d2ce1ddab944c93a0693ea5b285f746a36b0341d3b8f22f1645c6f5178ad7bf56aea67acd5749d63afbeebca2384b2ab35b1c9a330164bf84ac37d50556fd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
