# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f80b21bbd155bb94dd14e5f9127c5a9dd5a71f7d183f1c70f41510682531436fdb7fc8a7b3d16720962f8e6fcc2b2c5e87be125f143709cb3489365b1599ba6

test:
  secret_key_base: ef310e9d88a13f94d0032f4604035eb5ebc79f2d03d3f1b95f6b9b4cfea71013f2505466993f73add9eb4c585843e029c322f42db5156d03a960f1715f523e2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
